theme: jekyll-theme-cayman
title: "SemEval 2020 Task 1: Unsupervised Lexical Semantic Change Detection"
description: "SemEval 2020 Task 1: Unsupervised Lexical Semantic Change Detection"
#repository: "faustusdotbe/Unsupervised-Lexical-Semantic-Change-Detection-SemEval2020"
